version: '3.8'
services:
  postgre-db:
    image: postgres
    environment:
      - POSTGRES_USER=aloxide
      - POSTGRES_PASSWORD=localhost-pw2020
      - POSTGRES_DB=aloxide
    ports:
      - 5432:5432
