language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14

install:
  - npm i -g codecov
  - yarn
scripts:
  - yarn lerna bootstrap
  - yarn build
  - yarn test
after_success:
  - yarn test:coverage
  - codecov
